version: "3"

services:
  mysql:
    image: mysql
    container_name: account-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=fjdksla;
      - MYSQL_DATABASE=account
      - MYSQL_USER=zen
      - MYSQL_PASSWORD=fjdksla;
    volumes:
      - account-mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: account-phpmyadmin
    restart: always
    links:
      - mysql:db
    ports:
      - 5000:80


volumes:
  account-mysql:
    external: true
